#!/usr/bin/env python3
"""
Setup script for configuring API keys and testing the video generation system
"""

import os
import sys

def setup_env_file():
    """Setup the .env file with user's API keys"""
    print("🔧 Setting up EstateVision AI API Configuration")
    print("=" * 50)
    
    env_path = "/home/nahomkeneni/upwork_projects/chebude_dande/server/.env"
    
    # Read current .env file
    current_config = {}
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    current_config[key] = value
    
    print("\n📝 Please provide your API keys:")
    print("(Press Enter to keep current value or skip)")
    
    # Google Gemini API Key
    current_gemini = current_config.get('GOOGLE_GEMINI_API_KEY', 'your_google_api_key_here')
    gemini_key = input(f"\n🔑 Google Gemini API Key [{current_gemini}]: ").strip()
    if gemini_key:
        current_config['GOOGLE_GEMINI_API_KEY'] = gemini_key
    elif 'GOOGLE_GEMINI_API_KEY' not in current_config:
        current_config['GOOGLE_GEMINI_API_KEY'] = 'your_google_api_key_here'
    
    # OpenAI API Key (optional)
    current_openai = current_config.get('OPENAI_API_KEY', 'your_openai_api_key_here')
    openai_key = input(f"\n🔑 OpenAI API Key (optional) [{current_openai}]: ").strip()
    if openai_key:
        current_config['OPENAI_API_KEY'] = openai_key
    elif 'OPENAI_API_KEY' not in current_config:
        current_config['OPENAI_API_KEY'] = 'your_openai_api_key_here'
    
    # Set other default values
    defaults = {
        'DATABASE_URL': 'sqlite:///./estatevision_ai.db',
        'SECRET_KEY': 'your-secret-key-here-change-in-production',
        'ACCESS_TOKEN_EXPIRE_MINUTES': '30',
        'MAX_VIDEO_SIZE_MB': '100',
        'MAX_DESCRIPTION_LENGTH': '5000',
        'UPLOAD_FOLDER': './uploads',
        'CORS_ORIGINS': '["*"]'
    }
    
    for key, value in defaults.items():
        if key not in current_config:
            current_config[key] = value
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write("# EstateVision AI Configuration\n")
        f.write("# Generated by setup script\n\n")
        
        f.write("# Database\n")
        f.write(f"DATABASE_URL={current_config['DATABASE_URL']}\n\n")
        
        f.write("# Security\n")
        f.write(f"SECRET_KEY={current_config['SECRET_KEY']}\n")
        f.write(f"ACCESS_TOKEN_EXPIRE_MINUTES={current_config['ACCESS_TOKEN_EXPIRE_MINUTES']}\n\n")
        
        f.write("# Google APIs\n")
        f.write(f"GOOGLE_GEMINI_API_KEY={current_config['GOOGLE_GEMINI_API_KEY']}\n\n")
        
        f.write("# OpenAI (optional)\n")
        f.write(f"OPENAI_API_KEY={current_config['OPENAI_API_KEY']}\n\n")
        
        f.write("# Video Processing\n")
        f.write(f"MAX_VIDEO_SIZE_MB={current_config['MAX_VIDEO_SIZE_MB']}\n")
        f.write(f"MAX_DESCRIPTION_LENGTH={current_config['MAX_DESCRIPTION_LENGTH']}\n")
        f.write(f"UPLOAD_FOLDER={current_config['UPLOAD_FOLDER']}\n\n")
        
        f.write("# CORS\n")
        f.write(f"CORS_ORIGINS={current_config['CORS_ORIGINS']}\n")
    
    print(f"\n✅ Configuration saved to {env_path}")
    return current_config

def test_ffmpeg():
    """Test if ffmpeg is available"""
    print("\n🎬 Testing FFmpeg...")
    try:
        import subprocess
        result = subprocess.run(['ffmpeg', '-version'], capture_output=True, text=True)
        if result.returncode == 0:
            print("✅ FFmpeg is installed and working")
            return True
        else:
            print("❌ FFmpeg test failed")
            return False
    except FileNotFoundError:
        print("❌ FFmpeg not found. Please install FFmpeg:")
        print("   Ubuntu/Debian: sudo apt install ffmpeg")
        print("   macOS: brew install ffmpeg")
        print("   Windows: Download from https://ffmpeg.org/")
        return False

def test_api_keys(config):
    """Test API keys"""
    print("\n🔑 Testing API Keys...")
    
    # Test Google Gemini
    if config.get('GOOGLE_GEMINI_API_KEY') and config['GOOGLE_GEMINI_API_KEY'] != 'your_google_api_key_here':
        print("✅ Google Gemini API key configured")
    else:
        print("⚠️  Google Gemini API key not configured")
        print("   Get your key from: https://makersuite.google.com/app/apikey")
    
    # Test OpenAI
    if config.get('OPENAI_API_KEY') and config['OPENAI_API_KEY'] != 'your_openai_api_key_here':
        print("✅ OpenAI API key configured")
    else:
        print("ℹ️  OpenAI API key not configured (optional)")

def main():
    print("🚀 EstateVision AI Setup")
    print("This script will help you configure the video generation system\n")
    
    # Setup environment
    config = setup_env_file()
    
    # Test dependencies
    test_ffmpeg()
    test_api_keys(config)
    
    print("\n" + "=" * 50)
    print("🎉 Setup Complete!")
    print("\nNext steps:")
    print("1. Start the server: uvicorn app.main:app --reload")
    print("2. Open frontend and test video generation")
    print("3. Login with: username=admin, password=TempPass123")
    print("\nFor help, check the logs in the server console.")

if __name__ == "__main__":
    main()